### ISSUE TITLE
Implement filling of Observed World

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/carla-interface#4]
observed_world = fillFromCarlaWorld()

now that we have filled the map in #3, we need to add the information of the other agents: 
- observable state (pose, history)
- How to make e.g. BehaviorConstantVelocity and BehaviorIDMClassic work?
-> Driving Corridor for other agents must be filled. How? Is there something carla provides (routing)...

Demo: have a live view of observed World in BARK (all agents move in Carla and BARK)

**Comment by klemense1** [comment]
- Spawning all agents of carla with auto mode
- Reading the Carla-World at every time step
- Setting the Bark World to that
--> Next Demo Step: Both viewers (Bark, Carla) are next to each other visualing the same

**Comment by klemense1** [comment]
Improvements for viewer:
- TODO: switch off plotting of past history
- TODO: plot world_time at the top of the viewer
- TODO: delete half of the map
- TODO: implement field of view for CARLA and use field-of-view feature of BARK (follow the agent) --> use Matplotlib Viewer
- TODO: implement "follow-the-ego-agent) for pygame viewer
- TODO: init_state and goal is needed for trajectory --> currently we need to set it to dummy values --> is that a problem for the viewer which get's solved by "field of view"

--> if that's finished, we can wrap up this issue

**Comment by tin1254** [comment]
![Screenshot 2019-11-21 16:15:15](https://user-images.githubusercontent.com/22342030/69350602-297fb480-0c7a-11ea-9c47-8f25a108d66d.png)
![Screenshot 2019-11-21 16:15:31](https://user-images.githubusercontent.com/22342030/69350605-2a184b00-0c7a-11ea-961e-186f9d89f9cf.png)
@klemense1 Is this fine for testing? Or it is better to have only one to two roads?

**Comment by klemense1** [comment]
I would narrow it down even more, and try to not have any loops. What about those two:

![image](https://user-images.githubusercontent.com/10078680/69357662-c3992a00-0c85-11ea-8f37-567831f5f020.png)

**Comment by klemense1** [comment]
It seems like we cannot just rempove part of the open drive map, we would also need to modify the 3d representation

**Comment by klemense1** [comment]
Apparently, there is something wrong with routing in the carla map

- in the T-Intersection, the Bark model is taking a turn for a short time
1) Is the center line correct? Switch it on when plotting!
2) Check the routing using roadgraph.print_graph(...)

**Comment by klemense1** [comment]
Running both simulators in parallel isn't feasible as the bark plotting takes a lot of time
Improvements
1) Improve of Speed of Pygame Viewer
2) Enable to update the bark plot at a lower frequency

**Comment by klemense1** [comment]
We cannot find the controlled vehicle in Carla:
--> Can we implement a Camera-View or Birds-Eye View only following the conrolled ego vehicle?

**Comment by tin1254** [comment]
> Apparently, there is something wrong with routing in the carla map
> 
>     * in the T-Intersection, the Bark model is taking a turn for a short time
> 
> 
>     1. Is the center line correct? Switch it on when plotting!
> 
>     2. Check the routing using roadgraph.print_graph(...)
![Screenshot from 2019-12-02 18-30-33](https://user-images.githubusercontent.com/22342030/69981241-36ca5800-1532-11ea-9230-617511063978.png)
![Screenshot from 2019-12-02 18-34-59](https://user-images.githubusercontent.com/22342030/69981433-97f22b80-1532-11ea-8bd1-4f9001eff271.png)
The road structure is already broken with the original maps, in both map Town01 and Town02, some junctions are shown broken in bark, and some connections are disconnected in graphviz.

**Comment by klemense1** [comment]
Why is the connection fro road_id=239 lane_id=29 to road_id=0, lane_id=2?

Possibility 1:
There might be missing connection in the Carla xodr Map?

Possibility 2:
We misinterpret the standard? Can we look into the parser of Carla? How do they parse the xodr file?

**Comment by tin1254** [comment]
> Why is the connection fro road_id=239 lane_id=29 to road_id=0, lane_id=2?
> 
> Possibility 1:
> There might be missing connection in the Carla xodr Map?
> 
> Possibility 2:
> We misinterpret the standard? Can we look into the parser of Carla? How do they parse the xodr file?

A connection at the junction is certainly missing https://github.com/bark-simulator/carla-interface/issues/4#issuecomment-560503364 , a similar issue is also observed in another map (town01).

It may relate to the driving direction of lanes, but it is not defined according to standard.

**Comment by klemense1** [comment]
What do you mean with the driving direction relation? Can you elaborate on this?

**Comment by tin1254** [comment]
> What do you mean with the driving direction relation? Can you elaborate on this?

In the maps provided by carla, they defined the driving direction for every drivable lane. And also the 3D assets in Unreal map are also placed complied with right-handed driving direction.
By my empirical observations, as long as the ego follows the direction and with the issue https://github.com/bark-simulator/bark/issues/191 fixed, some of the routings on carla maps would be fine.

I have to do a thorough check at each junction to confirm whether my guess of the direction is true... I have already raised an issue on Carla repo

**Comment by klemense1** [comment]
Carla's direction is right-handed, however the map seems to only be valid for left-handed. We will wait for a response from the Carla issue. Until then, routing / centerline and so on cannot be used.
